### ISSUE TITLE
Bug de hashtag en markdown

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/bdx.town#1]
Les hashtags en fin de ligne (ou seuls sur une ligne) ne sont pas affichés quand on publie en markdown.

Il faut au moins un autre caractère (séparé par un espace) après le hashtag.

La piste du # utilisé pour les titres est à creuser.

**Comment by Cl0v1s** [comment]
Je suis en train de travailler dessus ! J'ai une bonne piste !

**Comment by Cl0v1s** [comment]
J'ai identifié le soucis, mais je n'arrive pas à le résoudre. Je vais implémenter un workaround qui devrait être satisfaisant. 

C'est un problème dans la dépendance Linkify de Pleroma.

**Comment by Cl0v1s** [comment]
Inclut dans la 1.1.2

**Comment by Dehelssey** [comment]
A priori c'est revenu.. cf mon post https://bdx.town/notice/ANHlVFhLbOfn5LVoRs il manque le hastag #charpentier à la fin de ma première phrase...

**Comment by Dehelssey** [comment]
Ce qui est marrant c'est que le post apparait quand même dans les résultats de recherche du hashtag concerné https://bdx.town/tags/charpentier
