### ISSUE TITLE
Ajout d'un gif-picker ?

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/bdx.town#3]
À voir si c'est vraiment une fonctionnalité utile / souhaitable niveau impact écologique (si on a un serveur éolien c'est pas pour spammer des gifs là ou des emojis suffiraient)

Je sais que ça a été implémenté sur radical.town et im-in.space si besoin de pistes techniques

On peut opter pour une banque libre plutôt (omg gifs je crois, de mémoire) que giphy aussi pour rester dans un truc plus respectueux

**Comment by Cl0v1s** [comment]
je vais regarder si y'a pas de piste optimisées/avec des limites de taille (genre pour éviter les gifs à 1MO)
Mais clairement, une option libre s'impose, je vais regarder tes propositions !

**Comment by Cl0v1s** [comment]
je ne trouve pas réellement d'alternatives à Giphy ou Tenor :/

**Comment by Dehelssey** [comment]
Juste pour centraliser les infos, on peut utiliser Oh My Gif, par ex via omg.phie.ovh

Et on part sur 1 gif par requête pour pas loader whatmille Mo

Et éventuellement la possibilité d'ajouter des gifs en fav pour les retrouver facilement

**Comment by Cl0v1s** [comment]
Inclut dans la 1.3.1 FE
