### ISSUE TITLE
Auto-suppression des médias après un délai X

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/bdx.town#5]
Pareil pour limiter le stockage nécessaire

**Comment by Dehelssey** [comment]
Piste technique → https://lord.re/posts/215-supprimer-ses-vieux-toots-sur-mastodon-ou-pleroma/

**Comment by Cl0v1s** [comment]
Voir https://github.com/Cl0v1s/bdx.town/issues/4
